apiVersion: apps/v1
kind: Deployment
metadata:
  name: redcap-nginx
  labels:
    app: redcap-nginx
    app.kubernetes.io/role: redcap-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redcap-nginx
  template:
    metadata:
      labels:
        app: redcap-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 1080
        volumeMounts:
        - mountPath: /var/www/redcap
          name: redcap-app
          readOnly: true
        - mountPath: /etc/nginx/conf.d/redcap.conf
          name: nginx-conf
          subPath: redcap.conf
        - name: nginx-tls
          mountPath: /etc/nginx/ssl
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: redcap-healthz
          mountPath: /var/www/redcap/healthz.php
          subPath: healthz.php
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nginx-tls
        secret:
          secretName: redcap-tls
      - name: redcap-app
        persistentVolumeClaim:
          claimName: redcap-app-pvc
      - name: nginx-conf
        configMap:
          name: redcap-nginx
          items:
          - key: redcap.conf
            path: redcap.conf
      - name: redcap-healthz
        configMap:
          name: redcap-healthz
          items:
            - key: healthz.php
              path: healthz.php
